### ISSUE TITLE
License

### ISSUE THREAD

**Issue by akatakritos** [thecadams/301RedirectModule#10]
Hi!

Thanks for your work on this project. It was easy to get up and running.

I'm interested in deploying this for my client, but I'm not altogether clear on what the license is. Could you add a LICENSE file or point out which, if any, license this is released under? Gotta make sure the lawyers are satisfied :wink: 

Thank you!

**Comment by thecadams** [comment]
Hi! Great to see this getting such serious attention. I went with the MIT license, but it's totally just a formality because I really don't mind what you do with the code as long as you use it.

Can you please advise if MIT is going to be OK with your lawyers, and if so, close this ticket?

**Comment by akatakritos** [comment]
That's perfect. Thank you!!

**Comment by thecadams** [comment]
You're welcome.
