### ISSUE TITLE
Is it possible to hide or group messages about redirect at Sitecore 8.1 ?

### ISSUE THREAD

**Issue by a3codeDA** [thecadams/301RedirectModule#19]
Hi, 
Is it exist any settings for hide/group notification about redirect to some item.
Some users don't want to see them.

**Comment by thecadams** [comment]
Hi! If there's logging right now, you might be able to increase the logging level and if that's not it, a config setting could be put in (I'd be happy to take a pull request)

Which log messages are you referring to?

**Comment by a3codeDA** [comment]
I customized this component for our needs

**Comment by thecadams** [comment]
No problem. Happy to help in future - and thanks for using the module!
