### ISSUE TITLE
Moving items in siteroot causes wrong requested Url

### ISSUE THREAD

**Issue by ThomasBaek** [thecadams/301RedirectModule#27]
When moving a item in the siteroot, the redirect module create a autogenrated redirect, but the requested Url is wrong.

Example:
Siteroot/Testmove is moved to Siteroot/child/testmove
The requested url is set to: //testmove

I believe it is because of this line in AutoCreateRedirectOnMove.cs. Getting the path to the oldParent when the parent is siteroot will result in a / as the url:
`string` oldPath = LinkManager.GetItemUrl(oldParent).Replace("/sitecore/shell", "") + "/" + `LinkManager.GetItemUrl(item).Split('/').Last();`

When added another / before the items new url with result in "//".

I have resolved this by modifying this a bit:

`var parentPath = LinkManager.GetItemUrl(oldParent).Replace("/sitecore/shell", "");
if (!parentPath.Equals("/") && parentPath.Length > 0)
		parentPath += "/";
string oldPath =  parentPath + LinkManager.GetItemUrl(item).Split('/').Last();`

**Comment by thecadams** [comment]
Hi, little update here. My Sitecore license has expired but as soon as I hear back from Sitecore sales I'll be able to test for you. In the meantime if you have a fix you're welcome to contribute it.

**Comment by thecadams** [comment]
cc @Chris-Castle I'm still waiting for a Sitecore license so I can test this.
