### ISSUE TITLE
Site level redirects

### ISSUE THREAD

**Issue by BhanuKorthiwada** [thecadams/301RedirectModule#35]
Considering an example below:

`www.example.com/policy` - redirect to global policy
`www.example.ca/policy` - redirect to policy page of Cannada only

As of now, redirects are global to all sites running in a sitecore node.
In **multisite solution**, it will be great if redirects are specific to a single site. We can fall back to global if needed.

Please see [master branch](https://github.com/BhanuKorthiwada/301RedirectModule) created by me, let me know your thoughts on this.

Note: Feature Branch is not code complete.

Wanted to know team taught before I complete it and send a pull request.

**Comment by thecadams** [comment]
This is looking good, going to take a look at it tonight. Don't forget to merge master, I just merged in a PR today.
