### ISSUE TITLE
your download link for the module is not working at the moment

### ISSUE THREAD

**Issue by Gangus** [thecadams/301RedirectModule#48]
I am currently interested in trying out your module but the link for the new Sitecore 9 verison http://trac.sitecore.net/301RedirectModule is not working. Could you please rehost this or fix the original link.

Thank you

**Comment by thecadams** [comment]
Heya, I'm not responsible for that trac link unfortunately, didn't even know it existed until you mentioned it.. I suggest you grab the code and build it yourself instead. Hope that helps.
