### ISSUE TITLE
Support Coremedia 10 - Version 2001.1/2001.2

### ISSUE THREAD

**Issue by mlauke** [thecadams/301RedirectModule#59]
hi,

not really an issue but just a question regarding cm 10 support. is it planned for near future? and if so, can u tell a potential release date? otherwise we'll fork it and maybe can contribute the working version.

kind regards

**Comment by thecadams** [comment]
Hi! I’ve had trouble getting a developer license to work on this module from Sitecore, they haven’t been willing to help me maintain this module, so I can accept a PR if it’s reviewed by someone from the community, but there’s no plans to support CoreMedia at this stage.

It shouldn’t be hard to add, my guess is CoreMedia is just a new Item Template so there’s just some more complexity obtaining the Item’s URL, but I may be wrong.

Apologies I can’t give a more helpful answer.

**Comment by mlauke** [comment]
no worries..., we managed to get the recent version with cm9 running. so we're try to update it.... thanx, so far.

**Comment by thecadams** [comment]
Great news, glad you got it (sort of) going. As I said wish I could help more!
