### ISSUE TITLE
Exact match pattern

### ISSUE THREAD

**Issue by aadidevsite** [thecadams/301RedirectModule#61]
Does the exact match redirect support # in the URL

We do have urls similar to the below in our site that we are trying to redirect to, but I think # character in the URL is creating a problem and does not work. Do I have another way to support this kind of URL? Appreciate your reply. 

https://testsite.com/xx/control-product/regulators/flow/regulator-295#!/prod-title=specialt-product-113

**Comment by thecadams** [comment]
The anchor is only seen by the backend in the browser; so this won't be possible with the RedirectModule without it loading a page in the browser to check whether there's an anchor supplied, which would unfortunately break all the existing behavior that depends on the 301 response (as opposed to a 200 that would then issue some type of JS based redirect)

You might want to consider building a page that does what I describe, and if you build it cleanly enough (ie. don't risk breaking any existing behavior), we could consider merging that as a new type of redirect.

**Comment by aadidevsite** [comment]
Thank you, makes sense.
